CREATE DATABASE IF NOT EXISTS SAMS;
USE SAMS;
CREATE TABLE Admin(
USERNAME VARCHAR(20) UNIQUE NOT NULL COLLATE UTF8MB4_BIN,
PASSWORD VARCHAR(20) UNIQUE NOT NULL COLLATE UTF8MB4_BIN
);

INSERT INTO ADMIN VALUES ("Admin1","Admin@123");

CREATE TABLE Student(
usn VARCHAR(25) PRIMARY KEY COLLATE UTF8MB4_BIN,
name VARCHAR(35) NOT NULL,
email VARCHAR(35) NOT NULL,
branch VARCHAR(10) NOT NULL, 
sem INT NOT NULL,
sec VARCHAR(3) NOT NULL
);

CREATE TABLE Teacher(
id VARCHAR(35) PRIMARY KEY,
password VARCHAR(35) UNIQUE NOT NULL COLLATE UTF8MB4_BIN, 
name VARCHAR(35) NOT NULL,
email VARCHAR(35) NOT NULL,
dept VARCHAR(10) NOT NULL, 
degree VARCHAR(30) NOT NULL
);

CREATE TABLE Subject(
sub_id VARCHAR(30) PRIMARY KEY,
sub_name VARCHAR(40) NOT NULL,
dept VARCHAR(10) NOT NULL
);

CREATE TABLE Attendance(
usn VARCHAR(25) NOT NULL COLLATE UTF8MB4_BIN,
tid VARCHAR(35) NOT NULL,
sub_id VARCHAR(30) NOT NULL,
sem INT NOT NULL,
sec VARCHAR(10) NOT NULL,
adate DATE NOT NULL,
astatus VARCHAR(30) DEFAULT "present" ,
FOREIGN KEY(usn) REFERENCES Student(usn) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(tid) REFERENCES Teacher(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(sub_id) REFERENCES Subject(sub_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE assignclass(
tid VARCHAR(35) NOT NULL,
sub_id VARCHAR(30) NOT NULL,
sem INT NOT NULL,
sec VARCHAR(10) NOT NULL,
dept VARCHAR(10) NOT NULL,
FOREIGN KEY(tid) REFERENCES Teacher(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(sub_id) REFERENCES Subject(sub_id) ON DELETE CASCADE ON UPDATE CASCADE
);

